# base image 
FROM node:22.5.1-alpine

# set working directory
WORKDIR /app

# copy package files
COPY package*.json ./

# install dependencies
RUN npm install

# only install production dependencies 
RUN npm ci --only=production

# copy project files
COPY . .

# expose port
EXPOSE 9000

# start app
CMD ["npm", "start"]
