# base image 
FROM node:22.5.1-alpine

# set working directory
WORKDIR /app

# copy package files
COPY package*.json ./

# install dependencies
RUN npm install

# only install development dependencies 
RUN npm ci --only=devleopment

# copy project files
COPY . .

# expose port
EXPOSE 7545

# start app
CMD ["npm", "run" , "dev"]
